### ISSUE TITLE
Any reason there isn't a build available for Windows?

### ISSUE THREAD

**Issue by TheWerewolf** [dji-sdk/FlightRecordParsingLib#28]
I mean, there are a LOT of Windows users out there. 
I'm pretty sure not all DJI drone users are MacOS or Ubuntu users.
Oddly, most of the third party parts include Visual Studio solution files, just none of the DJI parts.

If I port it to Windows, would DJI be interested in including it?

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/100997'>Zendesk ticket #100997</a>:<br><br>Unfortunately, we're not planning on adding Windows support at this time. But here's the cool part: since the library is open-source, you've got the freedom to modify it as needed to make it work just right for your Windows setup.
<br><p><em><small>°°°</small></em></p>

**Comment by TheWerewolf** [comment]
Heh, this is true – just that it feels like you guys chose the single hardest way to deliver this.

I’ll port it to .Net where it can work on Windows, MacOS, Linux, iOS and Android and post it on my Github. 😊

 

Thanks!
