### ISSUE TITLE
Building any part of this project fails. 

### ISSUE THREAD

**Issue by edancain** [dji-sdk/FlightRecordParsingLib#30]
Following your readme instructions on a Mac M2 Pro and on a Linux box fails. Attempting to run it in Docker fails. I shouldn't have to try to work out the issues running your project if I follow your readme. 

The CMakeLists.txt files, which there are many, references cmake_minimum_required as needing versions 3.4.1, 3.5. The latest release on their website is 3.29.6. 

Here is the last of the output where it errors when trying to run your /dji-flightrecord-kit/build/Mac/FlightRecordStandardization.cpp/generate.sh file on a Mac. 0 then 1 as input for dynamic library output:
(NB: it fails even faster if I don't change those cmake version refs.)

 "google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*)", referenced from:
      /Users/edancain/Airspacelink/FlightRecordParsingLib/dji-flightrecord-kit/build/Mac/FlightRecordStandardizationCpp/standardProtobufBuild/CMakeFiles/DJIProtobuf.dir/google/protobuf/testing/zcgzip.cc.o
  "google::protobuf::io::GzipOutputStream::~GzipOutputStream()", referenced from:
      /Users/edancain/Airspacelink/FlightRecordParsingLib/dji-flightrecord-kit/build/Mac/FlightRecordStandardizationCpp/standardProtobufBuild/CMakeFiles/DJIProtobuf.dir/google/protobuf/testing/zcgzip.cc.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [standardProtobufBuild/libDJIProtobuf.dylib] Error 1
make[1]: *** [standardProtobufBuild/CMakeFiles/DJIProtobuf.dir/all] Error 2
make: *** [all] Error 2

I have tried and tried to get the Sample to run, I am just at my wits end now with it. I think you guys are trying to do too much with this project. Yeah it probably just works on your computer right, that old chestnut, but trust me I can't get any of it to work. I have been changing your CMakeLists.txt where indicated that there is an erorr, but its just too many things going wrong that I have to punt this for now. 

I am happy to provide you with more error messages from both Mac, Ubuntu and trying to get it to build in Docker. Horrible, so I would be happy to help in anyway I can if it helps improve this.

Can you please try to improve your readme, and make this thing work out of the box following your instructions.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110950'>Zendesk ticket #110950</a>:<br><br>Is the FlightRecordParsingLib you are currently using the latest version? What version of CMake are you using? I was able to run the FlightRecordParsingLib sample code smoothly with CMake version 3.25.2, so I don't think the version is the root cause.


Could you please revert the changes you made on Cmake first, and then run FlightRecordParsingLib using the script located in this path? When prompted to enter input in the window, simply type 0. If you encounter any errors, could you provide us with the complete error message?
https://github.com/dji-sdk/FlightRecordParsingLib/blob/master/dji-flightrecord-kit/build/Mac/FRSample/generate.sh
<br><p><em><small>°°°</small></em></p>
